In [1]:
import math

In [4]:
import random

In [5]:
random.randint(10, 20)

15

In [3]:
import numpy as np

In [6]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
list1 = [1,2,3,4]
arr = np.array(list1)
print(list1)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [12]:
np.random.randint(10,20,3)

array([12, 15, 19])

In [13]:
np.random.randint(100,500,30)

array([272, 233, 428, 236, 494, 176, 212, 311, 458, 487, 397, 176, 410,
       343, 219, 211, 140, 285, 206, 263, 323, 226, 202, 203, 209, 318,
       291, 169, 412, 234])

In [14]:
import random              