In [4]:
import numpy as np

In [5]:
multi_list = [[1,2,3]]

In [6]:
list1 = [1,2,3,4]
np.ndim(list1)    # number of dimension

1

In [7]:
np.ndim(multi_list)

2

In [8]:
multi_list = [[1,2,3],[4,5,6]]
multi_list[0][1]     # multi-indexing

2

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
arr = np.zeros(12)

In [11]:
arr.reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
list1 = [1,2,3,4,5,6]
list1 = np.array(list1)  # converting tha list into an arry
print(list1.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [13]:
multi_list1 = [[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]
multi_list1 = np.array(multi_list1)
print(multi_list1.reshape(5,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [14]:
np.ndim(multi_list1)

3

In [15]:
multi_list1 = [[[1,2,3,4]],[[6,7,8,9]],[[11,12,13,14]],[[16,17,18,19]]]
multi_list1 = np.array(multi_list1)

In [16]:
multi_list1 =[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
multi_list1[0][1]

2

In [17]:
# ndim , arry , zeros , ones , reshape,

In [18]:
np.arange(10)  # arange function works same as range()--> but returns an array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [20]:
list_of_numbers = np.array([10,20,54,76,98,41,32])
np.mean(list_of_numbers)

47.285714285714285

In [21]:
np.std(list_of_numbers)

28.907311411842237

In [22]:
np.median(list_of_numbers)

41.0

In [23]:
np.var(list_of_numbers)

835.6326530612245

In [24]:
np.cov(list_of_numbers)

array(974.9047619)

In [25]:
multi_list = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
np.transpose(multi_list)   # transpose an array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
list1 = np.array([1,2,3,4,5,6])
list1.reshape(2,-1)   # -1 automatical deciedes the no. of columns

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr = np.array([1,2,3,4,5,6])
arr2 = arr[arr>3]

In [29]:
arr2

array([4, 5, 6])

In [30]:
arr.size     # to get tha lenght of array

6

In [31]:
arr.shape   # to get tha shape of array

(6,)

In [32]:
arr3 = np.array([1,2,3,3,4,4,4])
np.unique(arr3)          # extracts unique elements from an array

array([1, 2, 3, 4])

In [33]:
np.flip(arr3)          # reverses an array

array([4, 4, 4, 3, 3, 2, 1])

In [34]:
np.repeat(arr3,2)

array([1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4])

In [35]:
multi_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.max(multi_list[1])    # maximum of a multidimensional arry

6

In [37]:
multi1 = np.array([[1,2],[3,4]])
multi2 = np.array([[4,5],[6,7]])

In [38]:
np.dot(multi1,multi2)   # dot product of 2 matrices

array([[16, 19],
       [36, 43]])

In [39]:
print(multi1)
print(multi2)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


In [40]:
multi1.flatten()+multi2.flatten()

array([ 5,  7,  9, 11])

In [41]:
multi1.flatten()   # convert any dimensional arry to 1d

array([1, 2, 3, 4])

In [42]:
multi2.flatten()

array([4, 5, 6, 7])

In [43]:
arr = np.array([1,3,5,2,4,6])
arr.sort()
print(arr)

[1 2 3 4 5 6]
