<h2>NumPy</h2>
<h5>Library for scientific computing</h5>

In [1]:
import numpy as np

In [ ]:
# Array - 
# Sequence Type (like list)
# Homogenous - same data type only
# fixed length once created
# allows maipulation of data

In [4]:
# np.array function is used to create an array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
# if you give a numpy array values of different data types , it will convert all values to a single data type
arr2 = np.array(['Thanos',1,2,82.5])
arr2 # every value converted to string 

array(['Thanos', '1', '2', '82.5'], dtype='<U32')

In [6]:
# multidimensional array
multi_arr = np.array([[1,2,3],[4,5,6]])
multi_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# to check dimension of an array
multi_arr.ndim

2

In [ ]:
# check shape of an array
multi_arr.shape

(2, 3)

(2 - rows, 3 - columns)

In [ ]:
# total number of elements
multi_arr.size

6

In [ ]:
# datatype of an array 
arr2.dtype

dtype('<U32')

In [ ]:
# total bytes consumed by an array
arr2.nbytes

512

In [13]:
# np.zeros() - creates an array filled with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# np.ones - creates an array filled with ones
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# np.full(shape, fillvalue) - creates an array filled with a specific value
np.full(8, 32)

array([32, 32, 32, 32, 32, 32, 32, 32])

In [3]:
# np.eye() creates a matrix with 1 as diagonal and rest 0's
np.eye(9, 7,2) # 0 indicates the index where the diagobal should start from

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# np.arange() - like range function but returns an array
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
# np.linspace -> divides a range into even spaces and returns an array
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [ ]:
# to reverse an array - np.flip()
np.flip(arr2)

array(['82.5', '2', '1', 'Thanos'], dtype='<U32')

In [26]:
# np.random.randint() - generates a random integer
#   Syntax - (start , stop, no of integers)
np.random.randint(10, 20, 3)

array([15, 11, 18])

In [ ]:
# np.ravel() and arr.flatten() - flattens an array
np.ravel(multi_arr)

array([1, 2, 3, 4, 5, 6])

In [ ]:
multi_arr.flatten() 

array([1, 2, 3, 4, 5, 6])

In [ ]:
# arr.transpose() - turns column into rows and rows in columns
arr3 = np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3.transpose() 

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
# np.reshape() - reshapes an array
np.reshape(arr3, (6,2)) 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
#np.hstack() - stacks array horizontally
np.hstack(arr3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
# np.vstack() - stacks array vertically
np.vstack(arr3)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr_new = np.array([2,3,5,8,7,6])
np.split(arr_new,2) # splits the array into 2 new arrays

[array([2, 3, 5]), array([8, 7, 6])]

In [ ]:
arr_new2 = np.array([2,4,5,6,6,6,5,4,4])
np.unique(arr_new2) #returns unique values from an array

array([2, 4, 5, 6])

In [ ]:
np.sort(arr_new2) #sorts an array in ascending order

array([2, 4, 4, 4, 5, 5, 6, 6, 6])

In [ ]:
# np.where - retrurns elements depending on condition
np.where(arr_new % 2==0, "even","odd")

array(['even', 'odd', 'odd', 'even', 'odd', 'even'], dtype='<U4')

In [ ]:
# np.argmax
np.argmax(arr_new) # Returns 3 cause arr_new's maximum value is 8 which lies on 3rd index position

3

In [ ]:
np.argmin(arr_new) # opposite of argmax

0

In [36]:
# creating an array from another array
arr4 = np.array([1,2,3,4,5,6])
arr5 = arr4[arr4>3]
arr5

array([4, 5, 6])

In [ ]:
# arrays pointing to same memory location
arr6 = arr4
arr6[2] = 8
arr4 # value gets changed in arr4 also (3 to 8) since they point to same location in memory

array([1, 2, 8, 4, 5, 6])

In [42]:
arr7 = np.array([1,2,3,4])
arr8 = np.array([5,6,7,8])

In [ ]:
# Mathematical Operations on array (element-wise)
# additon
np.add(arr7, arr8)

array([ 6,  8, 10, 12])

In [44]:
# subtraction
np.subtract(arr7,arr8)

array([-4, -4, -4, -4])

In [45]:
# multiplication
np.dot(arr7, arr8)

70

In [ ]:
np.multiply(arr7, arr8)

array([ 5, 12, 21, 32])

In [ ]:
# division
np.divide(arr7, arr8)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
# exponent
np.power(arr7, arr8)

array([    1,    64,  2187, 65536])

In [ ]:
# modulus
np.mod(arr7, arr8)

array([1, 2, 3, 4])

In [ ]:
np.log(arr_new) # returns the natural log of each element in array

array([0.69314718, 1.09861229, 1.60943791, 2.07944154, 1.94591015,
       1.79175947])

In [ ]:
# dot product
multi_arr1 = np.array([[1,2],[4,5]])
multi_arr2 = np.array([[6,7],[9,10]])
np.dot(multi_arr1, multi_arr2)

array([[24, 27],
       [69, 78]])

In [61]:
# matrix multiplication
multi_arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
multi_arr4 = np.array([[3,4,5],[7,8,9],[9,10,11]])
np.matmul(multi_arr3, multi_arr4)

array([[ 44,  50,  56],
       [101, 116, 131],
       [158, 182, 206]])

In [ ]:
# Statistical functions
# mean - np.mean()
# median - np.median()
# standard deviation - np.std()
# variance - np.var()
# covariance - np.cov()
# percentile - np.percentile()