Numpy Functions

In [1]:
import numpy as np
#np.zeros(4)
#np.array([0,1,2])
#np.arange(4)
#np.empty(2)
#np.arange(2,9,2) 
#np.linspace(0,10, num=7) 
#x = np.ones(2 , dtype=np.int64)
arr = np.array([5,7,3,4,1,6])
#np.sort(arr)
arr2 = np.array([2 , 8 , 10])
#np.concatenate((arr , arr2), axis=0)
#arr.ndim
#arr.size
#arr.shape
#b = arr[arr<6]
#arr3 = arr.copy()
#arr3*arr
#.min() , .max(), .sum()
#arr.min(axis=0) - arr should be multidim
#rng = np.random.default_rng()  # the simplest way to generate random numbers #rng.random(3)
#rng.integers(5 , size=(4,2))
#np.unique(array_name)
#arr.transpose()
#a = np.flip(arr) #Reverse
#.flatten()
# ? - Info about the object , ?? - Source code
arr

array([5, 7, 3, 4, 1, 6])

In [2]:
import numpy as np

In [3]:
multi_list = [[1,2,3]]

In [4]:
list1 = [1,2,3,4]
np.ndim(list1) # number of dimensions

1

In [5]:
np.ndim(multi_list)

2

In [6]:
multi_list =[[1,2,3],[4,5,6]]
multi_list[0][1] #multi-indexing

2

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
arr = np.zeros(12) # creates an array of zeros

In [9]:
arr.reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
list1 = [1,2,3,4,5,6]
list1 = np.array(list1) #converting the list into an array
print(list1.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [11]:
# ndim , array, zeros, ones, reshape, 

In [12]:
np.arange(10) # arange function works same as range() --> but returns an array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [14]:
list_of_numbers = np.array([10,20,54,76,98,41,32])
np.mean(list_of_numbers) #mean

47.285714285714285

In [15]:
np.std(list_of_numbers) #standard deviation

28.907311411842237

In [16]:
np.median(list_of_numbers) #median

41.0

In [17]:
np.var(list_of_numbers) #variance

835.6326530612245

In [18]:
multi_list = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [19]:
np.transpose(multi_list) # transposes an array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
list1 = np.array([1,2,3,4,5,6])
list1.reshape(2,-1) # -1 automatically decides the no. of columns 

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr = np.array([1,2,3,4,5,6])
arr2 = arr[arr>3]

In [22]:
arr2

array([4, 5, 6])

In [23]:
arr.size # to get length of array

6

In [24]:
arr.shape # to get the shape of array

(6,)

In [25]:
arr3 = np.array([1,2,3,3,4,4,4])
np.unique(arr3) # extracts unique elements from an array

array([1, 2, 3, 4])

In [26]:
np.flip(arr3) # reverses an array

array([4, 4, 4, 3, 3, 2, 1])

In [27]:
np.repeat(arr3, 2)

array([1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4])

In [28]:
multi_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.max(multi_list) # maximum of a multidimensional array

9

In [30]:
multi1 = np.array([[1,2],[3,4]])
multi2 = np.array([[4,5],[5,6]])

In [31]:
np.dot(multi1,multi2) # dot product of 2 matrices

array([[14, 17],
       [32, 39]])

In [32]:
print( multi1)
print(multi2)

[[1 2]
 [3 4]]
[[4 5]
 [5 6]]


In [33]:
multi1.flatten() + multi2.flatten()

array([ 5,  7,  8, 10])

In [34]:
multi1.flatten() # converts any dimensional array to 1d

array([1, 2, 3, 4])

In [35]:
multi2.flatten()

array([4, 5, 5, 6])

In [36]:
import numpy as np

In [37]:
arr = np.array([1,"rah",5,2,4,6])
arr.sort()
print(arr)

['1' '2' '4' '5' '6' 'rah']


In [39]:
# If you give a numpy array values of different data types, it will convert all values to single dats type
arr2 = np.array(['Thanos',1,2,82.5])
arr2 # every value converted to string

array(['Thanos', '1', '2', '82.5'], dtype='<U32')

In [42]:
# multidimensional array
multi_arr = np.array([[1,2,3],[4,5,6]])
multi_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# to check the dimension of an array
multi_arr.ndim

2

In [44]:
# to check the shape of an array
multi_arr.shape

(2, 3)